<?xml version="1.0" encoding="utf-8"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="manip">

<!-- Rozmiary czlonow -->

<xacro:property name="sizes" value="${load_yaml('sizes.yaml')}"/>

<!-- Stawy -->

<xacro:property name="joints" value="${load_yaml('joints.yaml')}"/>

<xacro:property name="j1" value="prismatic"/>
<xacro:property name="j2" value="revolute"/>
<xacro:property name="j3" value="revolute"/>

<xacro:if value="${joints['fixed_joints']==True}">
  <xacro:property name="j1" value="fixed"/>
  <xacro:property name="j2" value="fixed"/>
  <xacro:property name="j3" value="fixed"/>
</xacro:if>

<!-- Parametry DH -->

<xacro:arg name="a1" default="0.5"/>
<xacro:arg name="a2" default="0.5"/>
<xacro:arg name="a3" default="0.5"/>

<xacro:arg name="d1" default="0.5"/>
<xacro:arg name="d2" default="0.5"/>
<xacro:arg name="d3" default="0.5"/>

<xacro:arg name="alpha1" default="0.5"/>
<xacro:arg name="alpha2" default="0.5"/>
<xacro:arg name="alpha3" default="0.5"/>

<xacro:arg name="t1" default="0.5"/>
<xacro:arg name="t2" default="0.5"/>
<xacro:arg name="t3" default="0.5"/>

<link name="base">
  <visual>
    <origin xyz="0 0 0.1" />
    <geometry>
      <box size="1 1 0.2"/>
    </geometry>
    <material name="white">
      <color rgba="1 1 1 1" />
    </material>
  </visual>

  <collision>
    <origin xyz="0 0 0.1" />
    <geometry>
      <box size="1 1 0.2"/>
    </geometry>
    <contact_coefficients mu="0" kp="1000.0" kd="1.0"/>
  </collision>
</link>

<joint name="base-el1" type="fixed">
  <parent link="base"/>
  <child link="el1"/>
  <origin xyz="0 0 0.2" rpy="0 0 0" />
</joint>

<link name="el1">
  <visual>
    <origin xyz="0 0 ${sizes['sizes']['l1']/2}" />
    <geometry>
      <cylinder radius="${sizes['sizes']['r1']}" length="${sizes['sizes']['l1']}"/>
    </geometry>
    <material name="white"/>
  </visual>

  <collision>
    <origin xyz="0 0 ${sizes['sizes']['r1']/2}" />
    <geometry>
      <cylinder radius="${sizes['sizes']['r1']}" length="${sizes['sizes']['l1']}"/>
    </geometry>
    <contact_coefficients mu="0" kp="1000.0" kd="1.0"/>
  </collision>
</link>

<joint name="el1-el2" type="${j1}">
  <parent link="el1"/>
  <child link="el2"/>
  <origin xyz="0 0 ${sizes['sizes']['l1']+0.1}" rpy="0 0 0" />
  <axis xyz="0 0 1" />
  <limit upper="0" lower="0.0" effort="10" velocity="10" />
</joint>

<link name="el2">
  <inertial>
    <mass value="1"/>
    <inertia ixx="100" ixy="0" ixz="0" iyy="100" iyz="0" izz="100" />
    <origin/>
  </inertial>

  <visual>
    <origin xyz="0 0 ${sizes['sizes']['l2']/2}" rpy="0 0 0" />
    <geometry>
      <cylinder radius="${sizes['sizes']['r2']}" length="${sizes['sizes']['l2']}"/>
    </geometry>
    <material name="white">
      <color rgba="1 1 1 1" />
    </material>
  </visual>

  <collision>
    <origin xyz="0 0 ${sizes['sizes']['l2']/2}" />
    <geometry>
      <cylinder radius="${sizes['sizes']['r2']}" length="${sizes['sizes']['l2']}"/>
    </geometry>
    <contact_coefficients mu="0" kp="1000.0" kd="1.0"/>
  </collision>
</link>

<joint name="el2-el3" type="${j2}">
  <parent link="el2"/>
  <child link="el3"/>
  <origin xyz="0 0 ${sizes['sizes']['l2']/2}" rpy="0 0 0" />
  <axis xyz="0 0 1" />
  <limit upper="0" lower="0.0" effort="10" velocity="10" />
</joint>

<link name="el3">
  <inertial>
    <mass value="1"/>
    <inertia ixx="100" ixy="0" ixz="0" iyy="100" iyz="0" izz="100" />
    <origin/>
  </inertial>

  <visual>
    <origin xyz="${sizes['sizes']['r2']+sizes['sizes']['r3']} 0 0"/>
    <geometry>
      <cylinder radius="${sizes['sizes']['r3']}" length="${sizes['sizes']['l3']}"/>
    </geometry>
    <material name="white">
      <color rgba="1 1 1 1" />
    </material>
  </visual>

  <collision>
    <origin xyz="${sizes['sizes']['r2']+sizes['sizes']['r3']} 0 0"/>
    <geometry>
      <cylinder radius="${sizes['sizes']['r3']}" length="${sizes['sizes']['l3']}"/>
    </geometry>
    <contact_coefficients mu="0" kp="1000.0" kd="1.0"/>
  </collision>
</link>

<joint name="el3-tool" type="${j3}">
  <parent link="el3"/>
  <child link="tool"/>
  <origin xyz="${2*sizes['sizes']['r3']} 0 0" rpy="0 0 0" />
  <axis xyz="0 0 1" />
  <limit upper="0" lower="0.0" effort="10" velocity="10" />
</joint>

<link name="tool">
  <inertial>
    <mass value="1"/>
    <inertia ixx="100" ixy="0" ixz="0" iyy="100" iyz="0" izz="100" />
    <origin/>
  </inertial>

  <visual>
    <origin xyz="${sizes['sizes']['l4']/2+sizes['sizes']['r3']} 0 0" />
    <geometry>
      <box size="${sizes['sizes']['l4']} ${sizes['sizes']['aa4']} ${sizes['sizes']['aa4']}"/>
    </geometry>
    <material name="white">
      <color rgba="1 1 1 1" />
    </material>
  </visual>

  <collision>
    <origin xyz="${sizes['sizes']['l4']/2+sizes['sizes']['r3']} 0 0" />
    <geometry>
      <box size="${sizes['sizes']['l4']} ${sizes['sizes']['aa4']} ${sizes['sizes']['aa4']}"/>
    </geometry>
    <contact_coefficients mu="0" kp="1000.0" kd="1.0"/>
  </collision>
</link>

</robot>
